spring:
  application:
    name: item-service
server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:2001/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
